### ISSUE TITLE
show the proc name

### ISSUE THREAD

**Issue by QQ2017** [tyranid/oleviewdotnet#17]
![image](https://user-images.githubusercontent.com/23667705/70048223-bde80080-1604-11ea-95a1-bfb3fc3f037f.png)

Why don't show the proc name?

For example, here are their real function names:

![image](https://user-images.githubusercontent.com/23667705/70048310-ed970880-1604-11ea-8a62-4f78b4700295.png)

**Comment by tyranid** [comment]
Unfortunately you can't get the names when the interface is derived from the COM proxy as the names just don't exist. You can if you get it from a type library or if that particular interface is implemented internal to the tool, but most interfaces aren't. In this case there's just not enough information.
