### ISSUE TITLE
What does `GetCategoryDesc` runtime crash mean?

### ISSUE THREAD

**Issue by LmTinyToon** [tyranid/oleviewdotnet#2]
I tryied to compile and run program and I got following runtime crash:

![image](https://cloud.githubusercontent.com/assets/20486820/25091161/54d970e2-2390-11e7-98e0-84499e666a9d.png)

**Comment by tyranid** [comment]
It just means that the COM category doesn't exist and COM returned an error (which converts to an exception in C#). This should be caught by the exception handler below, if it's not there some weird behaviour going on. Does this happen if you're not running in Visual Studio?

**Comment by LmTinyToon** [comment]
Yes, you are right. It works
