### ISSUE TITLE
"Value does not fall within the expected range" Exception after clicking view type library

### ISSUE THREAD

**Issue by hulucc** [tyranid/oleviewdotnet#3]
Very impressive tool! I'm looking for this for a long time.
But when I open type library of some entry which can be opened by oleview.exe, I got this exception.
![error](https://user-images.githubusercontent.com/4343900/27037172-b348c272-4fb9-11e7-9eb5-463da7bf8f0a.png)
Did I miss something? Thanks in advance.

**Comment by tyranid** [comment]
So there was a bug which meant that the application only looked for type libraries with the default '0' locale , which in the case of Session interface wasn't available. I've updated it now so hopefully it should now work. Get the pre-release of v1.3.1 in https://github.com/tyranid/oleviewdotnet/releases/tag/v1.3.1 and let me know if it fixes it.

**Comment by hulucc** [comment]
👍 It works.

**Comment by tyranid** [comment]
Okay will close this issue then.
