### ISSUE TITLE
TypeLib result are missing something

### ISSUE THREAD

**Issue by hulucc** [tyranid/oleviewdotnet#4]
for example:
the Mode property of Session(IID 000c109e-0000-0000-c000-000000000046) 
in oleview
```
[id(0x00000004), propget, helpcontext(0x000025e8)]
VARIANT_BOOL Mode([in] MsiRunMode Flag);
```
in vs2015(add %windir%\system32\msi.dll to project reference)

![_20170613114654](https://user-images.githubusercontent.com/4343900/27065126-1e6879f2-502e-11e7-83d2-a53d2fb2c79b.png)
![_20170613114720](https://user-images.githubusercontent.com/4343900/27065127-2086211c-502e-11e7-83b3-b512567e37b6.png)

in oleviewdotnet
```
bool Mode { get; set; }
```

**Comment by tyranid** [comment]
Well I wasn't exposing it in the output. I'm not going to support invoke these methods atm, I'm not really working on it but I've added support for displaying property parameters. I've not updated the release so you'll need to compile from source. Thanks for pointing this out.
