### ISSUE TITLE
A command line version

### ISSUE THREAD

**Issue by RadAd** [tyranid/oleviewdotnet#44]
Does anybody have a command line version that can output proxy definitions of interfaces in idl format?

**Comment by tyranid** [comment]
For interests sake I've now committed a formatter for proxies that outputs in IDL as well as an better implementation of type library parsing which no longer always converts to a .NET assembly and will format in IDL format. For example, you can now do `Get-TypeLib -Parse | Format-ComProxy` and it'll parse all type libraries and output as IDL text. Closing this issue.
