### ISSUE TITLE
Receive error message when attempting to view type library

### ISSUE THREAD

**Issue by enthusedcoder** [tyranid/oleviewdotnet#46]
I was attempting to "View type library" for the Microsoft Word 16.0 Object Library, but the tool failed to load the library and displayed the below error message instead:

```
Type 'Microsoft.Office.Core.MsoSyncEventType, 2df8d04c-5bfa-101b-bde5-00aa0044de52, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null' was not loaded in the ReflectionOnly context but the AssemblyBuilder was created as AssemblyBuilderAccess.ReflectionOnly.
```

Other than the error, very cool and useful tool.  Hope you can fix the issue.

![image](https://github.com/user-attachments/assets/a0cdbc26-1c6a-4de4-9b4e-ab4d9096d8ab)

**Comment by tyranid** [comment]
Hi, you're using a very old version of the tool. The latest source version has a new type library reading implementation which no longer relies on the .NET type library converter. I'd building a copy from source if you can.
![Screenshot 2024-10-07 193909](https://github.com/user-attachments/assets/309ac071-157c-46fd-a13a-ab09aecc2c4f)
