### ISSUE TITLE
Failed to build solution  [Metadata file not found + Impossible to locate resources file]

### ISSUE THREAD

**Issue by ntmessagebox** [tyranid/oleviewdotnet#47]
### Problem with the project solution.

When generating the solution i get all this Errors:

• Metadata file not found.
• Impossible to locate resources file.

See attached screenshot (in french) for files names:
![Screenshot_1](https://github.com/user-attachments/assets/165edab7-bffe-4200-83f5-d12a4e09461a)

**Comment by manisheretostay** [comment]
Here is how to resolve the build issues you may have.

I was using visual studio 2022 in this case.

![Screenshot 2024-12-01 101705](https://github.com/user-attachments/assets/f066e353-d268-4def-82e2-a5ea2a99c7eb)

use this project's Git repository .git link and add it there.

first select the sandbox-attacksurface-analysis-tool, as shown below and compile that. 
There may be some pop ups or dialog boxes asking you to use the recommended version of the .Net framework that is currently supported. 
Just choose your recommended version.
![image](https://github.com/user-attachments/assets/a4132a8f-b3ce-4ee8-ae88-bfe3febf5fc5)

compile your project, debug or release version, that is up to you. It should compile with no errors.

next go back to project view and select oleviewdotnet as shown below

![image](https://github.com/user-attachments/assets/7e2ecb39-d0a6-4a42-8395-5ff1841b7d03)

select oleviewdotnet as shown below

![image](https://github.com/user-attachments/assets/817a80a6-0932-4f84-bc83-55ca2a685e6f)

compile your project and all should be well.

Happy Days!!!!!!!

**Comment by tyranid** [comment]
Are you pulling in the submodules correctly? 

How it should work (and I should update the README to reflect this is) you clone the project using `git clone --recurse-submodules https://github.com/tyranid/oleviewdotnet.git`. Then it should build first time. I just tried this and it worked.

**Comment by ntmessagebox** [comment]
Thank you [manisheretostay](https://github.com/manisheretostay) for your great details using UI. However i utilized `git clone --recurse-submodules https://github.com/tyranid/oleviewdotnet.git` and it works perfectly.
