### ISSUE TITLE
Crash on property inspection

### ISSUE THREAD

**Issue by ToniSimi** [tyranid/oleviewdotnet#8]
Crash of release 1.5 with multiple of my interfaces in COMUtilities.cs in Line 2566 because p.GetMethod == null.
Misses verfication if getter only or setter only is implemented.

**Comment by tyranid** [comment]
I've added a fix, however I don't have any COM object to hand which has a setter but not a getter so if you have the chance it'd be nicer if you test it for me unless you know of one which is installed by default on the OS?

**Comment by ToniSimi** [comment]
Seems to work, does not crash anymore and shows the setter-only properties in the right pane. :-)
